name: Build Hugo
run-name: ${{ github.actor }} is building Hugo
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:h3ll0www0rld/hugo-blog.git
          BRANCH: main
          FOLDER: public
          MESSAGE: blog deploy
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}